version: "3"
services:
  fastapi:
    image: ghcr.io/shreyas-acharya/fastapi:${VERSION}
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_HOST=db
    restart: always
    volumes:
      - .:/App
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DATABASE}
        
volumes:
  postgres_data:
